# Generated by Django 5.2.5 on 2025-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fooditem_description_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
