# Generated by Django 5.2.5 on 2025-08-13 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_due_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('COGS-Other', 'COGS - other'), ('Payroll', 'Payroll'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Supplies', 'Supplies'), ('Marketing', 'Marketing'), ('Misc', 'Miscellaneous')], default='Misc', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
